grafana:
  initChownData:
    enabled: false

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

prometheus-node-exporter:
  enabled: false